apiVersion: v1
kind: Service
metadata:
  labels:
    app: netbox
  name: netbox
  namespace: netbox-stage
spec:
  ports:
  - name: 8001-tcp
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: netbox
    deploymentconfig: netbox
  sessionAffinity: None
  type: ClusterIP
sttus:
  loadBalancer: {}

